version: '3.1'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_USER: root
      MYSQL_USER: admin
      MYSQL_PASS: 123456
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--lower_case_table_names=1',
        '--default-time-zone=+8:00']
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/my.cnf:/etc/my.cnf
    restart: always # 设置容器自启模式
    ports:
        - 3306:3306

